[tools]
go = "1.25.5"

[env]
_.path = ["./build"]

[tasks.build]
description = "Build the project"
run = "go build -o build/rocket-debug -tags=remote"

[tasks.prod]
description = "Build project for end user"
run = "go build -o ~/bin/rocket -tags=remote -ldflags '-s -w'"

[tasks.format]
description = "Format codebase"
run = "gofmt -w ."
